# Generated by Django 5.1.5 on 2025-01-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="move",
            options={},
        ),
        migrations.AlterField(
            model_name="game",
            name="board",
            field=models.CharField(default="_________", max_length=9),
        ),
        migrations.AlterField(
            model_name="move",
            name="position",
            field=models.IntegerField(),
        ),
    ]
