# Generated by Django 5.1.5 on 2025-01-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_move_options_alter_game_board_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-last_move_time"]},
        ),
        migrations.AddField(
            model_name="game",
            name="last_move_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
